name: Bug Report
description: Report a bug or unexpected behavior in PvZ-Portable
labels: ["bug"]
body:
  - type: dropdown
    id: source
    attributes:
      label: Installation Source
      description: How did you obtain the PvZ-Portable binary?
      options:
        - Pre-built binary (from GitHub Releases or GitHub Actions)
        - Self-compiled from source
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: PvZ-Portable Version
      description: >
        Version or commit hash of PvZ-Portable you are using.
        You can find this from the release tag, or `git describe --tags`.
      placeholder: e.g. 0.1.4
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you running PvZ-Portable on?
      options:
        - Linux (x86_64)
        - Linux (aarch64)
        - Linux (riscv64)
        - Linux (loongarch64)
        - Linux (other)
        - Windows (x86_64)
        - Windows (arch64)
        - Windows (i686)
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Haiku
        - Nintendo Switch
        - Nintendo 3DS
        - Other
    validations:
      required: true

  - type: textarea
    id: os-info
    attributes:
      label: OS / Environment Info
      description: >
        Provide details about your operating system and environment.
        For Linux: distro name and version, kernel version, desktop environment, GPU driver, etc.
        For Windows: Windows version, GPU driver version.
        For macOS: macOS version, chip model.
        For consoles: firmware version, CFW version.
      placeholder: |
        e.g.
        Arch Linux, kernel 6.18.9, KDE Plasma 6, AMD Radeon Graphics
    validations:
      required: true

  - type: textarea
    id: build-deps
    attributes:
      label: Build Dependencies (self-compiled only)
      description: >
        If you compiled from source, list the versions of the key build dependencies.
        Include at least: compiler (GCC/Clang/MSVC), CMake, SDL2, zlib, libjpeg, libpng,
        libogg, libvorbis, libopenmpt, mpg123.
        You can get most of these from your package manager or `pkg-config --modversion`.
    validations:
      required: false

  - type: dropdown
    id: resource-version
    attributes:
      label: Resource Pack Version
      description: >
        Which version of the original PvZ game data are you using?
        The resource data (main.pak / properties) comes from different releases.
      options:
        - "1.2.0.1073 (Origin / PopCap GOTY)"
        - "1.2.0.1096 (Steam GOTY)"
        - Extracted / unpacked data
        - Unknown / Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Launch the game
        2. Go to '...'
        3. Click on '...'
        4. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: >
        If applicable, paste any relevant log output or attach screenshots / screen recordings.
        You can drag-and-drop images here.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful (e.g. workarounds tried, related issues).
    validations:
      required: false
